server {
    server_name mingas.by *.mingas.by;
    listen 443 ssl http2;
    ssl_certificate /etc/nginx/ssl/cert.crt;
    ssl_certificate_key /etc/nginx/ssl/cert.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE+AESGCM:ECDHE+CHACHA20:DHE+AESGCM:ECDHE+AES:DHE+AES;

    location / {
        include mime.types;
        default_type application/octet-stream;
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://nest_app:3000;
    }
}

server {
    listen 5555;
    server_name _;

    location / {
        proxy_pass http://nest_app:5555;
    }
}
server {
    server_name _;
    listen 50051 http2;
    location / {
        grpc_pass grpc://nest_app:50051;
    }
}
server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}