server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://nest_app:3000;
    }
    location /prisma/ {
        rewrite ^/prisma/(.*)$ /$1 break;
        proxy_pass http://nest_app:5555;
    }
}
server {
    server_name _;
    listen 50051 http2;
    location / {
        grpc_pass grpc://nest_app:50051;
    }
}